import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const target = url.searchParams.get('target') || 'system_database';

  const cleanTarget = target.replace(/https?:\/\//, '').replace(/[^a-z0-9.-]/gi, '_').toLowerCase();

  // In a real production scenario, this would execute `pg_dump` or connect to an S3 bucket to retrieve the backup.
  // We simulate a SQL dump file here for the local development experience.
  const dummySql = `-- Database Physical Dump Archive
-- Target: ${target}
-- Generated by Nexus SOC Autonomous Platform
-- Timestamp: ${new Date().toISOString()}

CREATE TABLE IF NOT EXISTS ${cleanTarget.replace(/[^a-z]/g, '')}_configs (
    id SERIAL PRIMARY KEY,
    key_name VARCHAR(255) UNIQUE NOT NULL,
    key_value TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ${cleanTarget.replace(/[^a-z]/g, '')}_users (
    uuid UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255),
    role VARCHAR(50) DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ${cleanTarget.replace(/[^a-z]/g, '')}_configs (key_name, key_value) VALUES 
('maintenance_mode', 'false'),
('active_theme', 'dark'),
('max_connections', '5000');

-- End of Backup Dump
`;

  return new NextResponse(dummySql, {
    status: 200,
    headers: {
      'Content-Type': 'application/sql',
      'Content-Disposition': `attachment; filename="${cleanTarget}_backup.sql"`,
    },
  });
}
